### ISSUE TITLE
[chain] - [multisite:new] [site:install] - Executing chain fails

### ISSUE THREAD

**Issue by brandonratz** [hechoendrupal/drupal-console#3197] opened 2017-02-21 20:37 UTC
**Version:** Drupal Console (1.0.0-rc16)

# Problem
Using command: 'multisite:new' followed by 'site:install' via chain command fails.

# Expected behavior
1. Creates multisite directory
2. Installs site via multisite uri

# Actual Behavior

1. Creates multisite directory
2. ERROR: Invalid multisite error

## Console Output

```
 // multisite:new

[OK] The new multisite structure was successfully created at "sites/test.example.com" and is ready for installation.

 // site:install

[ERROR] Invalid multisite, please create multisite using command drupal multisite:new test.example.com
         --site-uri=test.example.com`
```

## Chain file example

```
commands:
  - command: 'multisite:new'
    options:
        learning: true
        uri: 'http://test.example.com'
    arguments:
        directory: 'test.example.com'
        uri: 'http://test.example.com'
  - command: 'site:install'
    options:
        langcode: en
        db-type: mysql
        db-host: localhost
        db-name: test_example_dev
        db-user: root
        db-pass: root
        db-port: '3306'
        site-name: 'Example Website'
        site-mail: admin@example.org
        account-name: admin
        account-mail: admin@example.org
        account-pass: password
        learning: true
        uri: 'http://test.example.com'
    arguments:
        profile: lightning
```

**Comment by michaellenahan** [comment] 2017-03-15 16:57
Hello there! I met @enzolutions in the sprint room at Drupalcamp Iceland, and asked if there was somehow I could help to get started contributing to DrupalConsole.

He pointed me to this ticket. I'm saying this to warn you I'm a newbie to contributing here ...

I have cloned drupal-console to ~/workspace/drupal-console and the drupal site I am running it from is ~/workspace/drupal.template.

When I run the command with the supplied chain file, I get the following output.
```
$ cd ~/workspace/drupal.template/.
$ ~/workspace/drupal-console/bin/drupal chain --file=~/workspace/chain.yml --debug
✔ Creating request
➤ Creating Drupal kernel


  [Symfony\Component\Console\Exception\CommandNotFoundException]
  The command "multisite:new" does not exist.
```

**Comment by michaellenahan** [comment] 2017-03-15 17:06
I'm not sure why I'm getting:
```
The command "multisite:new" does not exist.
```
After all I can see the multisite:new command in the Repo. (It was added with this PR https://github.com/hechoendrupal/drupal-console/pull/2335/files)

**Comment by brandonratz** [comment] 2017-03-15 17:23
@michaellenahan Do you have a Drupal codebase you're running this against? 

```
composer create-project \
drupal-composer/drupal-project:8.x-dev \
drupal8.dev \
--prefer-dist \
--no-progress \
--no-interaction
```

What happens when you run `~/workspace/drupal-console/bin/drupal list`

**Comment by michaellenahan** [comment] 2017-03-15 17:55
Could it be that there is something missing in the service discovery?

If we look here: https://github.com/hechoendrupal/drupal-console/tree/master/config/services/drupal-console we can not find any multisite.yml --- maybe that is why I am getting the error "command does not exist" ?

**Comment by michaellenahan** [comment] 2017-03-15 17:58
Hi, @brandonratz 

"What happens when you run ~/workspace/drupal-console/bin/drupal list"

```

 [ERROR] The specified database connection is not defined: default                                                      

Drupal Console version 1.0.0-rc16

Usage:
  command [options] [arguments]

Options:
  -h, --help             Display this help message
  -q, --quiet            Do not output any message
  -V, --version          Display this application version
      --ansi             Force ANSI output
      --no-ansi          Disable ANSI output
  -n, --no-interaction   Do not ask any interactive question
  -e, --env[=ENV]        The Environment name [default: "prod"]
      --root[=ROOT]      Define the Drupal root to be used in command execution
      --debug            application.options.debug
      --learning         Generate a verbose code output
  -c, --generate-chain   Shows command options and arguments as yaml output to be used in chain command
  -i, --generate-inline  Shows command options and arguments as inline command
  -d, --generate-doc     Shows command options and arguments as markdown
  -t, --target[=TARGET]  Site name you want to interact with (for local or remote sites)
  -l, --uri=URI          URI of the Drupal site to use (for multi-site environments or when running on an alternate port)
  -y, --yes              Skip confirmation and proceed
  -v|vv|vvv, --verbose   Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  about                    Display basic information about Drupal Console project
  chain                    Chain command execution
  check                    System requirement checker
  exec                     Execute an external command.
  help                     Displays help for a command
  init                     Copy configuration files.
  list                     Lists all available commands
 chain
  chain:debug              List available chain files.
 settings
  settings:debug           List user Drupal Console settings.
  settings:set             Change a specific setting value in DrupalConsole config file
 site
  site:debug (sd)          List all known local and remote sites.
  site:new                 Download a new Drupal project
 yaml
  yaml:diff (yd)           Compare two YAML files in order to find differences between them.
  yaml:get:value           Get a value for a specific key in a YAML file.
  yaml:merge (ym)          Merge two or more YAML files in a new YAML file. Latest values are preserved.
  yaml:split (ys)          Split a YAML file using indent as separator criteria
  yaml:unset:key           Unset a YAML key in a YAML file.
  yaml:update:key (yu)     Replace a YAML key in a YAML file.
  yaml:update:value (yuv)  Update a value for a specific key in a YAML file.

 [WARNING] In order to list all of the available commands you should install drupal first.                              

```

**Comment by brandonratz** [comment] 2017-03-15 18:19
Ahh yes, this because you're _not_ running the command against an initialized Drupal codebase. Sorry some of this is out of my realm of experience but I'll do my best to explain.

Drupal console needs to run as a dependency in your Drupal project. Installation docs are here: https://github.com/hechoendrupal/drupal-console

The project scaffold should look something like this:

```
./project/composer.json
./project/vendor
./project/console
./project/webroot (drupal codebase)
```

If you run `vendor/drupal/console/bin/drupal list` command inside this initialized directory (./project), you should see in addition:

```
 multisite
  multisite:debug          List all multisites available in system
  multisite:new            Sets up the files for a new multisite install.
```

If there is a database defined for _default_ with a Drupal site installed, you'll get a myriad of other command options.

**Comment by michaellenahan** [comment] 2017-03-16 15:53
Thank you @brandonratz - it was exactly as you said - there was something wrong with my drupal installation - I re-downloaded https://github.com/drupal-composer/drupal-project and was able to see multisite:new in my list.

I was thus able to reproduce the problem you reported in your original post.

The problem is in src/Utils/Site.php:200

    if (isset($sites[$uri]) && is_dir($this->appRoot . "/sites/" . $sites[$uri])) {

Specifically: ```$sites[$uri]``` is not set.

The reason for this is that ```$uri``` has a value such like ```test.example.com```, but the ```$sites``` array incorrectly has a key of ```http://test.example.com```.

So where was this key incorrectly set?

The problem is with the previous command 'multisite:new'.

src/Command/Multisite/NewCommand.php:162

    $sites_file_contents .= "\n\$sites['$uri'] = '$this->directory';";

This is incorrect because this adds the text:

    $sites['http://test.example.com'] = 'test.example.com';

... to sites.php.

The correct text in sites.php should be:

    $sites['test.example.com'] = 'test.example.com';

So the fix is to change ```src/Command/Multisite/NewCommand.php:162``` to be the following:

    $sites_file_contents .= "\n\$sites['$this->directory'] = '$this->directory';";

**Comment by michaellenahan** [comment] 2017-03-16 16:05
https://github.com/hechoendrupal/drupal-console/pull/3232

**Comment by jmolivas** [comment] 2017-04-08 21:40
Fixed with PR https://github.com/hechoendrupal/drupal-console/pull/3232

**Closed by jmolivas** 2017-04-08 21:40 UTC
