### ISSUE TITLE
[site:status] Configuration directory with unescaped string.

### ISSUE THREAD

**Issue by GuidoRobertone** [hechoendrupal/drupal-console#3955] opened 2018-10-16 02:53 UTC
### Problem/Motivation
The result of site status command returns an unescaped config directory string when the settings.php file was edit.

### How to reproduce
1. Set config directory as $config_directories['sync'] = '../config/sync';
![screenshot_2018-10-15_23-14-53](https://user-images.githubusercontent.com/2628259/46989333-1b548180-d0d3-11e8-9f42-df42404a08d4.png)
2. run drupal site:status
3. An unescaped string is shown (Configuration directory: <em class="placeholder">sync</em>)
![screenshot_2018-10-15_22-50-48](https://user-images.githubusercontent.com/2628259/46989470-9c137d80-d0d3-11e8-9a9a-ba0b5d4745af.png)

**Details to include:**
- Drupal version : 8.5.6
- Console version : 1.8.0
- Console Launcher version : 1.8.0

### Solution
A correct directory string will be displayed using strip_tags() function.

**Comment by LOBsTerr** [comment] 2018-10-17 08:34
@GuidoRobertone First of all I have checked the code https://github.com/hechoendrupal/drupal-console/blob/912508f5465962877659480198802c43231e1057/src/Command/Site/StatusCommand.php#L158

Tags striping is there. 
I have tried to reproduce this, but unfortunately I'm not able.
When I run this command I don't see **Configuration directory** information there.
I even installed lighting profile and still it is not there. 
The only difference there I have Drupal 8.6.1

**Comment by LOBsTerr** [comment] 2018-10-17 08:53
@GuidoRobertone Ok, After debugging how Drupal displays system requirements. I was able to reproduce it. Actually, the config directory should exist in order to see in system requirements. In my case these folders were there. OK, now I see and I will debug it.

**Comment by LOBsTerr** [comment] 2018-10-17 09:37
PR - https://github.com/hechoendrupal/drupal-console/pull/3958
ok, I wrapped titles to strip_tags and it will solve the current issue, but we still issue with data now there will be no value for **Configuration directory**, because of a bug I have just found

https://www.drupal.org/project/drupal/issues/3007260

I think we also should display description as additional information. I need to find to present it nice way.
Anyway, it could be done in a separate ticket

**Comment by LOBsTerr** [comment] 2018-10-17 09:42
@GuidoRobertone I also added description information, like this users will see more additional information.

**Comment by LOBsTerr** [comment] 2019-04-05 11:09
Merged

**Closed by LOBsTerr** 2019-04-05 11:09 UTC
