### ISSUE TITLE
`config:import:single` not works 

### ISSUE THREAD

**Issue by igasi** [hechoendrupal/drupal-console#3223] opened 2017-03-10 16:00 UTC
### Problem/Motivation
I was running the command `drupal config:import:single config.name --file=path/to/config.name.yml` and I got the message

```
 // config:import:single
 
 [OK] Configuration(s) "", has been imported successfully.                                                                                                                                                                    
```

Apparently, the configuration has been imported, but

* The information about the config.name not appears.
* Importing or overwriting the configuration was not performed

**Details to include:**
- Why are we doing this? Above all, a summary should explain why a change is needed, in a few short sentences.

### How to reproduce

1. Prepare a config drupal yml file valid. e.g. system.site.yml (you can export from drupal)
2. Modify some value into the system.site.yml
2. Run
```
drupal config:import:single system.site --file=path/to/system.site.yml
```

**Details to include:**
- Drupal version
`Drupal 8.3.0-rc1`
- Console version
```
drupal/console                        1.0.0-rc16         The Drupal CLI. A tool to generate boilerplate code, interact with and...
drupal/console-core                   1.0.0-rc16         Drupal Console Core
drupal/console-en                     1.0.0-rc16         Drupal Console English Language
drupal/console-extend-plugin          0.4.0              Drupal Console Extend Plugin

```
- Console Launcher version
```
Drupal Console version 1.0.0-rc16
```

### Solution
Ensure that 

* this line https://github.com/hechoendrupal/drupal-console/blob/master/src/Command/Config/ImportSingleCommand.php#L86
be an Array.
* and this https://github.com/hechoendrupal/drupal-https://github.com/hechoendrupal/drupal-console/blob/master/src/Command/Config/ImportSingleCommand.php#L106 can use the $file when exist.

**Comment by jmolivas** [comment] 2017-03-28 07:59
Fixed with https://github.com/hechoendrupal/drupal-console/pull/3224

Thanks @igasi

**Closed by jmolivas** 2017-03-28 07:59 UTC

**Comment by csandanov** [comment] 2017-04-18 04:29
When I execute

```bash
$ drupal -vvv cis --name "search_api.server.solr_6_4" --file search-api-solr-server.yml
```

I get ` [ERROR] Value can not be empty`, worked fine before with the stable version. Is this the same issue? Using RC-16 version of console. Should I use dev-master from composer to fix it?

**Comment by csandanov** [comment] 2017-04-18 04:50
After upgrading to dev-master the command stopped working at all:

```bash
$ drupal cis --help
ArgumentCountError: Too few arguments to function Drupal\Console\Command\Generate\CommandCommand::__construct(), 4 passed and exactly 5 expected in /var/www/html/vendor/drupal/console/src/Command/Generate/CommandCommand.php on line 68 #0 [internal function]: Drupal\Console\Command\Generate\CommandCommand->__construct(Object(Drupal\Console\Generator\CommandGenerator), Object(Drupal\Console\Extension\Manager), Object(Drupal\Console\Utils\Validator), Object(Drupal\Console\Core\Utils\StringConverter))
#1 phar:///usr/local/bin/drupal/vendor/symfony/dependency-injection/ContainerBuilder.php(928): ReflectionClass->newInstanceArgs(Array)
#2 phar:///usr/local/bin/drupal/vendor/symfony/dependency-injection/ContainerBuilder.php(468): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), 'console.generat...')
#3 /var/www/html/vendor/drupal/console/src/Application.php(170): Symfony\Component\DependencyInjection\ContainerBuilder->get('console.generat...')
#4 /var/www/html/vendor/drupal/console/src/Application.php(41): Drupal\Console\Application->registerCommands()
#5 phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php(122): Drupal\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/vendor/drupal/console/bin/drupal.php(68): Symfony\Component\Console\Application->run()
#7 phar:///usr/local/bin/drupal/src/Utils/Launcher.php(30): include_once('/var/www/html/v...')
#8 phar:///usr/local/bin/drupal/bin/drupal.php(86): Drupal\Console\Launcher\Utils\Launcher->launch('/var/www/html', Object(Composer\Autoload\ClassLoader))
#9 phar:///usr/local/bin/drupal/bin/drupal(3): require('phar:///usr/loc...')
#10 /usr/local/bin/drupal(10): require('phar:///usr/loc...')
#11 {main}
ArgumentCountError: Too few arguments to function Drupal\Console\Command\Generate\CommandCommand::__construct(), 4 passed and exactly 5 expected in Drupal\Console\Command\Generate\CommandCommand->__construct() (line 68 of /var/www/html/vendor/drupal/console/src/Command/Generate/CommandCommand.php).
```

**Comment by jmolivas** [comment] 2017-04-18 14:31
@csandanov can you try rebuild caches `drupal cr all`

**Comment by csandanov** [comment] 2017-04-18 16:40
@jmolivas didn't help

**Comment by jmolivas** [comment] 2017-04-18 21:51
@csandanov I will try and ping you back

**Comment by csandanov** [comment] 2017-04-19 06:34
@jmolivas thank you, you can reproduce the error by running [Drupal 8 tests](https://github.com/wodby/docker4drupal/blob/master/test/8/7.1/test.sh) from docker4drupal project, just uncomment the tests and run `make test drupal=8 php=7.1` from the repository root. The image with Drupal code (installed via composer template) is wodby/drupal:8-7.1

**Comment by ultimike** [comment] 2017-07-01 15:27
I am seeing this exact same behavior with 1.0.0-rc20. 

![depanthconfig_ _-bash_ _120x48_and_local_development_and_notes](https://user-images.githubusercontent.com/1727889/27763355-3f4e196c-5e50-11e7-8dbc-7ff8163a315a.png)

**Comment by jmolivas** [comment] 2017-07-01 22:13
@ultimike The `config:import:single` command file option is expecting a full file path

<img width="829" alt="drupal-config-import-single" src="https://user-images.githubusercontent.com/366275/27765733-a19d33aa-5e6e-11e7-8414-a6d5e8d18d21.png">

Same for inline mode 
```
drupal config:import:single  \
--name="block.block.default_block" \
--file="/Users/jmolivas/Desktop/block.block.default_block.yml"
```
<img width="1115" alt="drupal-config-import-single-2" src="https://user-images.githubusercontent.com/366275/27765751-5c0d8e42-5e6f-11e7-9477-bd1c751b0d5e.png">

**Comment by jmolivas** [comment] 2017-07-01 22:35
@ultimike @csandanov @igasi  I think we can use only `file` option and remove `name` since we can obtain name from file ie:

`/Users/jmolivas/Desktop/block.block.default_block.yml` => `block.block.default_block`

**Comment by jmolivas** [comment] 2017-07-02 05:45
I did some changes on the command removing the `name` option and be used like:

Interactive mode:
```
drupal config:import:single 
```
<img width="1105" alt="drupal-config-import-single-3" src="https://user-images.githubusercontent.com/366275/27767514-cd0b97f8-5eae-11e7-867f-9754572cf596.png">

Providing a `file` option using full path
```
drupal config:import:single \
--file="/Users/jmolivas/Desktop/block.block.default_block.yml"
```
Providing `file` and `directory` options
```
drupal config:import:single  \
--file="block.block.default_block.yml" \
--directory="/Users/jmolivas/Desktop/"
```
<img width="1180" alt="drupal-config-import-single-4" src="https://user-images.githubusercontent.com/366275/27767518-d98c5238-5eae-11e7-97a3-c39b2eb2c288.png">

**Comment by ultimike** [comment] 2017-07-03 15:09
Excellent - thanks!

-mike

**Comment by bartvanhoutte** [comment] 2017-11-29 17:02
FYI, the --file option does not work with home directories (~):

ie: ~/releases/release-x/config/sync/some.config.yml

You need to provide the path without :

ie: /home/userx/releases/release-x/config/sync/some.config.yml

**Comment by hughworm** [comment] 2019-04-11 11:46
I ran into this in Drupal Console version 1.8.0. Using a path relative to the current directory gave this error. Changing the path of  --directory to be relative to the Drupal root made it work.

**Comment by msshaylaj** [comment] 2019-11-26 20:45
Hi there,
Wondering if there's a way to import multiple config files in one command. Thanks!
