### ISSUE TITLE
[ *console* ] PHP Warning:  pcntl_exec(): Error has occurred: (errno 2) No such file or directory in phar:///usr/local/bin/drupal/src/Utils/Launcher.php on line 34

### ISSUE THREAD

**Issue by sinyayadynya** [hechoendrupal/drupal-console#3321] opened 2017-05-25 11:49 UTC
### Problem/Motivation
I not able to run the drupal console anymore on my mac.

### How to reproduce
While entering any drupal command from a site, I'm getting the following message: 

PHP Warning:  pcntl_exec(): Error has occurred: (errno 2) No such file or directory in phar:///usr/local/bin/drupal/src/Utils/Launcher.php on line 34
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/drupal:0
PHP   2. require() /usr/local/bin/drupal:10
PHP   3. require() phar:///usr/local/bin/drupal/bin/drupal:3
PHP   4. Drupal\Console\Launcher\Utils\Launcher->launch() phar:///usr/local/bin/drupal/bin/drupal.php:70
PHP   5. pcntl_exec() phar:///usr/local/bin/drupal/src/Utils/Launcher.php:34

Warning: pcntl_exec(): Error has occurred: (errno 2) No such file or directory in phar:///usr/local/bin/drupal/src/Utils/Launcher.php on line 34

Call Stack:
    0.0002     356488   1. {main}() /usr/local/bin/drupal:0
    0.0011     399808   2. require('phar:///usr/local/bin/drupal/bin/drupal') /usr/local/bin/drupal:10
    0.0013     414760   3. require('phar:///usr/local/bin/drupal/bin/drupal.php') phar:///usr/local/bin/drupal/bin/drupal:3
    0.0028     518136   4. Drupal\Console\Launcher\Utils\Launcher->launch() phar:///usr/local/bin/drupal/bin/drupal.php:70
    0.0028     518608   5. pcntl_exec() phar:///usr/local/bin/drupal/src/Utils/Launcher.php:34

**Details:**
- Console version: 
(composer show | grep drupal/console)
drupal/console-core                   1.0.0-rc19              Drupal Console Core
drupal/console-extend-plugin          0.6.0               Drupal Console Extend Plugin
- Console Launcher version : 1.0.0-rc19

- I have tried to reinstall drupal console-core, but this do not help.

**Comment by jmolivas** [comment] 2017-05-26 08:50
@sinyayadynya Can you try updating to latest RC20 and validate is this still happening.

Make sure you update Launcher and Site installation.

**Comment by krisgraham** [comment] 2017-05-26 18:05
I'm having the same issue with updated console (1.0.0-rc20).

**Comment by jmolivas** [comment] 2017-05-26 18:45
@krisgraham did you updated Launcher and Site installation ?

**Comment by krisgraham** [comment] 2017-05-26 18:59
Yep, latest Launcher (re-installed today) and the site installation is up-to-date Lightning as of a few days ago. Also, when I remove the global Launcher and rely on the site's version of Console, I get the error from https://www.drupal.org/node/2825235
That is even after I update drupal-console for that site.

**Comment by jmolivas** [comment] 2017-05-26 19:01
@krisgraham can you try a `composer show | grep drupal/console` ot confirm which version do you have on the site?

**Comment by krisgraham** [comment] 2017-05-26 19:03
Yep:
drupal/console                        1.0.0-rc20          The Drupal CLI. A tool to generate boilerplate code, interact with an...
drupal/console-core                   1.0.0-rc20          Drupal Console Core
drupal/console-en                     1.0.0-rc20          Drupal Console English Language
drupal/console-extend-plugin          0.6.0               Drupal Console Extend Plugin

**Comment by mark-schaal** [comment] 2017-05-27 02:52
Confirming that I had something similar happen today with a fresh installation of the Lightning profile. I didn't see the note from https://drupalconsole.com/articles/add-drupalconsole-to-a-project-using-acquia-lightning-distribution about using `--no-install` with Lightning, so I followed the second set of instructions and wound up with the following:

```
$ composer show | grep drupal/console
drupal/console                        1.0.0-rc20          The Drupal CLI. A tool to generate boilerplate code, interact with and debug Dru...
drupal/console-core                   1.0.0-rc20          Drupal Console Core
drupal/console-en                     1.0.0-rc20          Drupal Console English Language
drupal/console-extend-plugin          0.6.0               Drupal Console Extend Plugin
```

**Comment by jmolivas** [comment] 2017-05-27 03:05
@mark-schaal it does work?

**Comment by mark-schaal** [comment] 2017-05-27 03:07
No same error as above with @krisgraham of 
```
PHP Warning:  pcntl_exec(): Error has occurred: (errno 2) No such file or directory in phar:///usr/local/bin/drupal/src/Utils/Launcher.php on line 41

Warning: pcntl_exec(): Error has occurred: (errno 2) No such file or directory in phar:///usr/local/bin/drupal/src/Utils/Launcher.php on line 41
```

Looking at this closer, it seems to be referencing as if I was using the global package installer, but I believe the latest Lightning composer-based install is following the local-project approach. Do I need to walk the drupal/composer package backwards to a different release perhaps?

**Comment by jmolivas** [comment] 2017-05-27 03:07
@mark-schaal did you updated the Launcher as well ?

Try `drupal self-update`

**Comment by mark-schaal** [comment] 2017-05-27 03:11
Yes, and saw:
```
$ drupal self-update
Checking for updates from version: "1.0.0-rc20"
The latest version "1.0.0-rc20" of DrupalConsole Launcher,
was already installed on your system.

If you want to update the DrupalConsole dependency
in your current site: /Users/mschaal/Dropbox/Web Applications/Drupal/acquia-drupal2/visarcdemo-dev
Execute: composer update drupal/console --with-dependencies
```

**Comment by mark-schaal** [comment] 2017-05-27 03:13
I followed that up with this:
```
$ composer require drupal/console:~1.0 \
> --prefer-dist \
> --optimize-autoloader \
> --sort-packages \
> --no-update

$ composer update drupal/console --with-dependencies
```

**Comment by mark-schaal** [comment] 2017-05-27 03:20
FWIW I do think that for all three users the situation is that the global launcher was removed in favor of local composer installations, and with lightning if you execute relative to the top level directory `bin/drupal` it seems to respond correctly without searching for the Launcher config.

**Comment by jmolivas** [comment] 2017-05-27 16:08
@mark-schaal the Launcher is optional. Glad to read site installation `bin/drupal` works properly.

**Comment by krisgraham** [comment] 2017-05-28 01:22
Confirmed that either with the global launcher installed or not, the only way this is working is by directly calling `bin/drupal` directly from within the lightning project.

**Comment by jmolivas** [comment] 2017-05-28 17:38
@krisgraham I do have a couple of lightning installation where I am  using DrupalConsole Launcher without any issues.

Not sure what could be your issue, let me know if you want to debug this.

**Comment by jmolivas** [comment] 2017-05-29 18:50
Closing this one. Feel free to re-open if still happening after updating to the latest version.

**Comment by sinyayadynya** [comment] 2017-06-05 16:03
Sorry to give late feedback, but it still do not work with the latest RC20 version.

My current project is a Commerce one, not lightning.

Also, I'm not sure to get what @mark-schaal pointed out about  top level directory. Could that be a work around? What should I do?

Thanks for help.

**Comment by jmolivas** [comment] 2017-06-07 03:41
@sinyayadynya did you  updated to latest Launcher you can by executing `drupal self-update`

**Comment by RishiKulshreshtha** [comment] 2017-06-07 10:24
@jmolivas, I'm getting the exact same issues mentioned by @mark-schaal and @krisgraham at https://github.com/hechoendrupal/drupal-console/issues/3321#issuecomment-304423647 and https://github.com/hechoendrupal/drupal-console/issues/3321#issuecomment-304486656 respectively.

FYI, I'm using

- [Lightning](https://www.drupal.org/project/lightning) distribution
- Drupal VM (details are mentioned below)
- Behind Corporate Firewall/Proxy

```
macOS 10.12 (16A323)
Vagrant 1.9.5
VirtualBox 5.1.22r115126
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Jul 30 2016, 18:31:42) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

Hope this might help to find the exact issue.

**Comment by krisgraham** [comment] 2017-06-08 01:47
I still see this issue with lightning distribution (acquia/lightning-project) but not drupal-composer/drupal-project.

**Comment by sinyayadynya** [comment] 2017-06-08 09:05
I'm not on lightning, but drupal/commerce

**Comment by sinyayadynya** [comment] 2017-06-08 09:23
Actually the Drupal Console (1.0.0-rc21) update solved my issue. Big Thanks!

**Comment by jmolivas** [comment] 2017-06-09 02:39
Closing this one. Feel free to comment if still happening after updating to the latest version.

**Closed by jmolivas** 2017-06-09 02:39 UTC
