### ISSUE TITLE
Error: Call to a member function discoverModules() on null

### ISSUE THREAD

**Issue by blasvicco** [hechoendrupal/drupal-console#3415] opened 2017-07-11 18:35 UTC
### Error: Call to a member function discoverModules() on null

The issue title should comply with the following structure:

[ command:module:dependency:install ] discoverModules() on null in Command/Shared/ModuleTrait.php on line 29

### Problem/Motivation
Performing this command call in the console result in the next error:
Error: Call to a member function discoverModules() on null in ../drupal-console/src/Command/Shared/ModuleTrait.php on line 29

**Details to include:**
- We should handle the exception

### How to reproduce
Calling the console command
drupal   module:dependency:install

**Details to include:**
- Drupal version 8.3.5.
- Console version 1.0.0-rc23.
- Console Launcher version 1.0.0-rc21.

### Solution
In file ../drupal-console/src/Command/Shared/ModuleTrait.php add before call to "$this->extensionManager->discoverModules()"
if (!$this->extensionManager)
throw new \Exception('No extension manager available.');

**Comment by LOBsTerr** [comment] 2018-03-09 09:49
@blasvicco I have tested for example like this 
```
drupal module:dependency:install  entity_embed
```
I can't reproduce it. Can you please check it with the latest version ?

**Comment by LOBsTerr** [comment] 2018-03-19 21:37
Closing the issue due to no reply. Feel free to reopen it.

**Closed by LOBsTerr** 2018-03-19 21:37 UTC
