### ISSUE TITLE
[generate:entity:content] .module registers wrong render element

### ISSUE THREAD

**Issue by vierlex** [hechoendrupal/drupal-console#3878] opened 2018-04-25 14:10 UTC
### Problem/Motivation
Generated strings in .module and the produced *.html.twig file don't match up and produce empty content when viewing the entity for the first time.

### How to reproduce
- Drupal version 8.5.2
- Console version 1.8
- Steps to reproduce

- generate an entity via the drupal console with the generate:entity:content command
- look into your generated .module file: the twig template is registered with the 'render element' being 'children'
- look into your generated */templates/*.twig file: inside the if, 'content' is checked, not 'children'

### Solution
Set the 'render element' to 'content' in the *.module:*_theme() hook

**Comment by LOBsTerr** [comment] 2018-04-26 08:12
@vierlex If you check the code more carefully, you will see that we handle preprocessing in default_entity.page.inc file (it can have different name in your case)
```
/**
 * Implements hook_theme().
 */
function mz_theme() {
  $theme = [];
  $theme['default_entity'] = [
    'render element' => 'elements',
    'file' => 'default_entity.page.inc',
    'template' => 'default_entity',
  ];
  $theme['default_entity_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'default_entity.page.inc',
  ];
  return $theme;
}
```
and here we set content variable 
```
function template_preprocess_default_entity(array &$variables) {
	//var_dump($variables);
  // Fetch DefaultEntity Entity Object.
  $default_entity = $variables['elements']['#default_entity'];

  // Helpful $content variable for templates.
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
```

By default you should see at least a user who added the entity. If you added some custom fields, they are rendered correctly also. I have checked it.

**Comment by vierlex** [comment] 2018-04-26 17:31
So this is what my (unedited) theme hook, which differs quite a bit.

`function person_theme() {
  return [
    'person' => [
      'render element' => 'children',
    ],
  ];
}`

Note: I dont use bundles, maybe that might be the cause?

**Comment by LOBsTerr** [comment] 2018-04-26 21:11
@vierlex I found where this code comes from. Actually it is generated by generate:module command.
So, you have generated your module, which is called person.
When you generate the content entity without bundles it doesn't generate theme function and related template.
The code above is not related to your content entity.
In fact, the current generated skeleton uses standard routes to display entity.
Try to use this command:
```
drupal generate:entity:content  --module="person" --entity-class="PersonEntity" --entity-name="person_entity" --base-path="/admin/structure" --label="Person entity" --is-translatable --revisionable --uri="http://default" --no-interaction
```
It will generate person entity in your person module.
Then open admin/structure/person_entity and add entity.
if you open the entity you will see there is only title and user who created the current content.
It looks for me everything is ok here. If you add custom fields, you will see more information.
![entity](https://user-images.githubusercontent.com/537500/39332140-dd786998-49a6-11e8-9d71-5bf8fd1c020b.jpg)

**Comment by LOBsTerr** [comment] 2018-07-12 22:35
Closing the issue feel free to reopen it

**Closed by LOBsTerr** 2018-07-12 22:35 UTC

**Comment by GiorgosK** [comment] 2019-01-16 05:20
@LOBsTerr 
I have create custom entity with `1.8.0` and ONLY the theme function is not created/updated 
one needs to put the following in `.module` file in order for the `message_entity.html.twig` to be picked up.

```
/**
 * Implements hook_theme().
 */
function message_theme() {
  $theme = [];
  $theme['message_entity'] = [
    'render element' => 'elements',
    'file' => 'message_entity.page.inc',
    'template' => 'message_entity',
  ];
  $theme['message_entity_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'message_entity.page.inc',
  ];
  return $theme;
}
```
Is that by design ? or should it be filled as a bug ?

**Comment by philwolstenholme** [comment] 2021-01-08 19:23
This is still an issue - I just scaffolded a new custom content entity and `hook_theme` was missing from the generated files, despite a `templates/ENTITY_NAME.html.twig` directory and file being generated.
