### ISSUE TITLE
[command:server] Problems to start drupal server

### ISSUE THREAD

**Issue by viniciusgava** [hechoendrupal/drupal-console#3177] opened 2017-02-13 03:21 UTC
### Problem/Motivation
I cannot run the drupal using comand `./vendor/bin/drupal server localhost:8888` after already has installed using php -S command. 

**Details to include:**
**Error when try to open the drupal**
> Warning: Unknown: Filename cannot be empty in Unknown on line 0
> 
> Fatal error: Unknown: Failed opening required '' (include_path='.:') in Unknown on line 0

I trying to use drupal console server just because I cannot edit a field of a. content type using `php -S` , I received a error:
> Not Found
The requested resource /admin/structure/types/manage/article/fields/node.article.body was not found on this server.

### How to reproduce
1. Download drupal
2. Start the installation using php -S localhost:8888 and continue with installation on browser
3. Add the drupal/console dependency then run `./vendor/bin/drupal server localhost:8888`
 
### Version info
- Drupal: 8.2.6
- Drupal Console (1.0.0-rc16)
- PHP 7.0.15
- OS: Mac OS X El Capitan 10.11.6

**Comment by belaustegui** [comment] 2017-02-14 07:29
Same bug happening here. Using the `drush runserver` command works fine though.

**Comment by jmolivas** [comment] 2017-02-14 15:10
@viniciusgava @belaustegui  The missing fie is the `router.php` file included on the project you need to copy to your system by executing the `init` command and select your home directory as destination.

**Comment by belaustegui** [comment] 2017-02-15 08:19
@jmolivas I can confirm that the problem is gone after running `drupal init`.

**Comment by viniciusgava** [comment] 2017-02-19 21:37
@jmolivas Thank you, It's work. I did not know that I had to run `drupal init`.

**Comment by jmolivas** [comment] 2017-06-07 06:51
Closing this one. Feel free to comment if still happening after updating to the latest version and following provided instructions.

**Closed by jmolivas** 2017-06-07 06:51 UTC
Labels: bug
