### ISSUE TITLE
[config:import] Fails when  skip-validate-site-uuid: true and default lang is not english

### ISSUE THREAD

**Issue by hudri** [hechoendrupal/drupal-console#3881] opened 2018-05-02 08:20 UTC
### Problem/Motivation
I want to install a site from an existing multilingual configuration with a non-english default language. When I run drupal config:import it fails with error message 

`An error occurred while trying to write the config file: "Can not delete the default language"`

### How to reproduce

- Drupal version 8.5.3
- Console version 1.8.0

1. Set up a new minimal instance of Drupal with a non-english default lang (in my case: 'de')
2. Copy existing configuraion from another site (in my case: default lang 'de', additional lang 'en') to default sync directory
3. Make sure  `skip-validate-site-uuid: true` is set in console's `config.yml`
4. `drupal config:import --no-interaction` fails with error message as above

I don't know how to debug this, even though I've included -vvv I didn't get any debug info except the error message.
Problem might be related to this core issue: https://www.drupal.org/project/drupal/issues/2856021

### Solution
None, but there is a simple workaround: Running the same import command a 2nd time fixes the issue, the import runs without any error message. The workaround from core issue above seems not applicable because I explicitly want to use `skip-validate-site-uuid`

**Comment by marcelovani** [comment] 2018-08-06 11:31
I am having the same problem when installing Thunder and importing config.

# Reproducing the problem with Thunder
Here are the steps to reproduce (Assuming you already have the Thunder codebase)
1. Enable skip config
` drupal settings:set overrides.config.skip-validate-site-uuid true`

1. Install Thunder
`drupal site:install thunder --no-interaction --force`

1. Export config
`drupal config:export`

1. Repeat Step 1

1. Import config
`drupal config:import`

You will see the error: 
`An error occurred while trying to write the config file: "Can not delete the default language"`

# Reproducing the problem with a custom profile
To make it simple, I created a very small profile that has a dependency on **Language**

1. Create _my_profile.info.yml_ into _profiles/contrib_ folder
```yaml
name: My Profile
type: profile
description: 'Build a custom site without pre-configured functionality. Suitable for advanced users.'
version: VERSION
core: 8.x
dependencies:
  - node
  - block
  - dblog
  - page_cache
  - dynamic_page_cache
  - language
themes:
  - stark
```

1. Enable skip config
` drupal settings:set overrides.config.skip-validate-site-uuid true`

1. Install My Profile
`drupal site:install my_profile --no-interaction --force`

1. Export config
`drupal config:export`

1. Repeat Step 2

1. Import config
`drupal config:import`

You will see the error: 
`An error occurred while trying to write the config file: "Can not delete the default language"`

# The cause
This error happens when you install profiles that require Language mofule.

# The Fix
I don't know how to fix it in Drupal Console but there is a way to hack it on the profile.
Create _my_profile.install_ into _profiles/contrib_ folder
```php
<?php
function my_profile_install() {
  $sync = \Drupal::service('config.storage.sync');
  $langs = [
    'language.entity.en',
    'language.entity.und',
    'language.entity.zxx',
  ];
  foreach ($langs as $lang) {
    if ($sync_lang = $sync->read($lang)) {
      $config = \Drupal::configFactory()->getEditable($lang);
      $config->set('uuid', $sync_lang['uuid']);
      $config->save();
    }
  }
}
```

Now try to repeat steps 1 to 5.

Result:
`[OK] Configuration imported successfully.`

**Comment by gilbertomangones** [comment] 2019-09-18 21:59
Hi, 
**Import the configuration files from a site to other one**

Steps

1.  Install Drupal 8 (English)

- ```$ composer create-project drupal-composer/drupal-project:8.x-dev drupal2 --stability dev --no-interaction````

- ```$ drupal site:install```

![1](https://user-images.githubusercontent.com/6983125/65188587-60480d00-da34-11e9-908c-bf4bfe4b5919.png)

![2](https://user-images.githubusercontent.com/6983125/65188607-6a6a0b80-da34-11e9-8fce-164c23cd68db.png)

![3](https://user-images.githubusercontent.com/6983125/65188621-72c24680-da34-11e9-8958-d7489dd0cafb.png)

2. Install site # 2 the same way (In this case “es” Spanish)
```$ composer create-project drupal-composer/drupal-project:8.x-dev drupal1 --stability dev --no-interaction````
```$ cd drupal1/````
```$ drupal site:install````
![4](https://user-images.githubusercontent.com/6983125/65188743-bddc5980-da34-11e9-9744-edebd70f2ffa.png)
![5](https://user-images.githubusercontent.com/6983125/65188754-c2a10d80-da34-11e9-9450-8088e8cc201a.png)

3. After installed both sites, in the English site several changes were made, in this case
In the English site (drupal2), Enable some modules and remember another site was installed in Spanish.

![8](https://user-images.githubusercontent.com/6983125/65188831-e5332680-da34-11e9-9c2b-74afa5b26bbb.png)

4. After having made the previous changes, are exported the config files

```$ drupal config:export --no-interaction````
![9](https://user-images.githubusercontent.com/6983125/65188879-04ca4f00-da35-11e9-9fe9-3ddb0220c3f6.png)

![14](https://user-images.githubusercontent.com/6983125/65188944-34795700-da35-11e9-80d3-63ea0f8737f8.png)

5. The files generated in sites 2 (English) with the new changes (enabled modules) to the sites 2 (Spanish), this files generated are copied to the Drupal1 in the same path.

![9](https://user-images.githubusercontent.com/6983125/65188973-4bb84480-da35-11e9-8d0c-bfe704d9ca23.png)

6. in the site Spanish (drupal1) to apply

```$ cd  drupal1/````
```$ drupal settings:set overrides.config.skip-validate-site-uuid true````
```$ drupal config:import --no-interaction````

![10](https://user-images.githubusercontent.com/6983125/65189057-87530e80-da35-11e9-92da-5cd0cc1e3ece.png)

**Comment by enzolutions** [comment] 2019-09-18 22:05
The warnings are related to the fact that the second side doesn't have English as language. I will close this issue

**Closed by enzolutions** 2019-09-18 22:05 UTC

**Comment by dravenk** [comment] 2019-12-08 05:31
Not work with docker and composer-drupal.
```
 [ERROR] The "/root/.console/config.yml" config file is missing, try executing `drupal init`                            
```
<img width="859" alt="fail" src="https://user-images.githubusercontent.com/14295318/70384741-e5511b80-19be-11ea-89bd-83a008d1abaf.png">
<img width="1111" alt="fail2" src="https://user-images.githubusercontent.com/14295318/70384742-e5511b80-19be-11ea-9981-3271b5c24a16.png">
