### ISSUE TITLE
[module:uninstall] Can't uninstall module if it is in the profile list

### ISSUE THREAD

**Issue by ddrozdik** [hechoendrupal/drupal-console#1916] opened 2016-02-12 09:49 UTC
Hi, 

 I have a custom profile in my Drupal installation. This profile contains list of modules (https://github.com/DmitryDrozdik/dmaps/blob/master/d8/profiles/pp/pp.info.yml), which should be installed during installation Drupal profile. 

After successful installation, I can not uninstall module(dmaps), added to the profile list. But I should be able to do this. Uninstalling module works well on the Drupal "uninstall page".

**Comment by darol100** [comment] 2016-02-16 11:51
@DmitryDrozdik Do you know if you can uninstall from the UI ? I just curios if this is expected behavior from DrupalCore not allowing uninstall dependency from profiles.

**Comment by DmitryDrozdik** [comment] 2016-02-16 13:26
@darol100 yes, of course I can. Drupal profile - this is installation profile, it will be used  when you install the Drupal. But after installation, you can do everything you want with your modules.

**Comment by alexbarrett** [comment] 2017-04-27 13:56
This still seems to be an issue. I wanted to uninstall the core search module but was unable to do so with Drupal Console.

    $ drupal mou search
    
    [ERROR] Unable to uninstall modules "search" because are required by "standard"

Uninstalling via the admin/modules/uninstall page works fine.

**Comment by cburschka-pwc** [comment] 2017-07-06 17:53
Simple missing-line bug, looks like.

core:

```php
      $profile = drupal_get_profile();
      while (list($module) = each($module_list)) {
        foreach (array_keys($module_data[$module]->required_by) as $dependent) {
          if (!isset($module_data[$dependent])) {
            // The dependent module does not exist.
            return FALSE;
          }

          // Skip already uninstalled modules.
          if (isset($installed_modules[$dependent]) && !isset($module_list[$dependent]) && $dependent != $profile) {
            $module_list[$dependent] = $dependent;
          }
        }
      }
```

UninstallCommand:

```php
            $dependencies = [];
            while (list($module) = each($moduleList)) {
                foreach (array_keys($moduleData[$module]->required_by) as $dependency) {
                    if (isset($installedModules[$dependency]) && !isset($moduleList[$dependency]) && $dependency != $profile) {
                        $dependencies[] = $dependency;
                    }
                }
            }
```

You can actually see the `$profile` variable get marked as undefined in the IDE.

**Comment by jmolivas** [comment] 2017-07-06 18:14
Another option is to pass `--force`

**Comment by jmolivas** [comment] 2017-07-06 18:15
```
drupal mou search --force
```

**Closed** 2017-07-13 18:02 UTC
Labels: bug
