### ISSUE TITLE
[config:export] Doesn't export languages folder

### ISSUE THREAD

**Issue by killua99** [hechoendrupal/drupal-console#1736] opened 2016-01-14 20:13 UTC
Problem:

When I ran `drupal config:export` it didn't export the entire settings, I'm missing languages. When I ran the drupal UI export or the drush command: `drush cex sync` it import the languages settings.

Solution:

Achieve the same behavior as Drupal Core UI or drush (but better ;D ) and don't miss multi-languages settings.

**Comment by enzolutions** [comment] 2016-01-14 20:15
@killua99 can you list the id of files missing, thanks

**Comment by killua99** [comment] 2016-01-14 20:30
$ ls ../config/sync/language/sv/
block.block.adminimal_theme_breadcrumbs.yml
block.block.adminimal_theme_content.yml
block.block.adminimal_theme_help.yml
block.block.adminimal_theme_login.yml
block.block.adminimal_theme_page_title.yml
block.block.adminimal_theme_primary_local_tasks.yml
block.block.adminimal_theme_secondary_local_tasks.yml
contact.form.personal.yml
core.date_format.fallback.yml
core.entity_form_mode.user.register.yml
core.entity_view_mode.block_content.full.yml
core.entity_view_mode.node.full.yml
core.entity_view_mode.node.rss.yml
core.entity_view_mode.node.search_index.yml
core.entity_view_mode.paragraph.preview.yml
core.entity_view_mode.taxonomy_term.full.yml
core.entity_view_mode.user.compact.yml
core.entity_view_mode.user.full.yml
field.field.block_content.basic.body.yml
field.field.paragraph.body_image.field_body_image.yml
field.field.paragraph.hottest.field_content.yml
field.field.user.user.user_picture.yml
filter.format.plain_text.yml
language.entity.en.yml
language.entity.sv.yml
language.entity.und.yml
language.entity.zxx.yml
node.type.content.yml
paragraphs.paragraphs_type.map.yml
search.page.node_search.yml
search.page.user_search.yml
shortcut.set.default.yml
system.action.node_delete_action.yml
system.action.node_make_sticky_action.yml
system.action.node_make_unsticky_action.yml
system.action.node_promote_action.yml
system.action.node_publish_action.yml
system.action.node_save_action.yml
system.action.node_unpromote_action.yml
system.action.node_unpublish_action.yml
system.maintenance.yml
system.menu.admin.yml
system.menu.footer.yml
system.menu.tools.yml
taxonomy.vocabulary.tags.yml
tour.tour.language-add.yml
tour.tour.language-edit.yml
tour.tour.language.yml
tour.tour.locale.yml
tour.tour.views-ui.yml
user.mail.yml
user.role.administrator.yml
user.settings.yml
views.view.archive.yml
views.view.block_content.yml
views.view.content_recent.yml
views.view.content.yml
views.view.files.yml
views.view.frontpage.yml
views.view.glossary.yml
views.view.taxonomy_term.yml
views.view.user_admin_people.yml
views.view.who_s_new.yml
views.view.who_s_online.yml

All of them was missing. Before I didn't run any drush command. I was exporting only with console and then I did the drush cex sync the entire language folder was added in my active directory I  compare it and saw the results and indeed before running the drush command the entire folder  languages and all those files was missing only drush add them not drupal console

**Comment by juanramonperez** [comment] 2017-08-29 18:58
any plans for this?

**Comment by cburschka-pwc** [comment] 2017-08-30 12:26
Is this a duplicate of #3182 / #3185? In that case it should be working now.

However, it doesn't currently create the folders for the languages. This'll be fixed by #3482 which seems to be scheduled for 1.0.2. For now, it should be possible to fix this by first extracting the configuration from a tar.gz, to put the folder structure in place.

**Comment by jmolivas** [comment] 2017-08-31 06:52
@killua99 @enzolutions  @cburschka-pwc @juanramonperez PR https://github.com/hechoendrupal/drupal-console/pull/3482 merged

**Closed by jmolivas** 2017-08-31 06:52 UTC
Labels: bug
