### ISSUE TITLE
[database:connect] No database key besides `default` is recognized

### ISSUE THREAD

**Issue by illepic** [hechoendrupal/drupal-console#3778] opened 2018-02-12 02:36 UTC
Running any `database:` command against any database key defined in `settings.php` **besides** `default` results in an error.

For instance, with a `settings.php` consisting of:

```php
$databases['default']['default'] = array (
  'database' => 'downfall_d8',
  'username' => 'root',
  'password' => 'root',
  'prefix' => '',
  'host' => 'localhost',
  'port' => '3306',
  'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
  'driver' => 'mysql',
);

$databases['migrate']['default'] = [
  'database' => 'migrate',
  'username' => 'root',
  'password' => 'root',
  'host' => 'localhost',
  'port' => '3306',
  'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
  'driver' => 'mysql',
  'prefix' => 'demo_',
];
```

and then running:

```bash
vendor/bin/drupal database:connect migrate
```

results in:

```bash
[ERROR] Database "migrate" connection info wasn't found
```

whereas running:

```bash
vendor/bin/drupal database:connect default
```

results in:

```bash
Connection: "mysql -A --database=downfall_d8 --user=root --password=root --host=localhost --port=3306"
````

## Details

- I am using Drupal Console as installed locally by the [Drupal Composer project](https://github.com/drupal-composer/drupal-project).
- The `migrate` database is currently empty. I am hoping to let `vendor/bin/drupal database:restore` do its thing and import a Drupal 6 sql dump into the `migrate` database
- The `migrate` database entry was added to `settings.php` via the `vendor/bin/drupal database:add` command.

## Versions
- Drupal version: 8.4.4
- Console version: 1.5.0
- Console Launcher version: 1.5.0 (but Drupal Console is **only** installed locally to the project via composer).

**Comment by LOBsTerr** [comment] 2018-02-12 17:10
The problem is that connection can be establish based on **key** and **target**. So, get proper information we need to accept the **target** argument, which by default should have value "default".

**Comment by illepic** [comment] 2018-02-12 17:36
@LOBsTerr, I'll give this a shot when I get back to that dev machine tonight:

```bash
vendor/bin/drupal database:connect --target=migrate
```

(Did I infer that correctly?)

**Comment by LOBsTerr** [comment] 2018-02-12 20:03
@illepic I was thinking about having two arguments. Something like this:

```
drupal database:connect migrate default
```

```
drupal database:connect key target
```
If it is not passed we use "default" value.

**Comment by illepic** [comment] 2018-02-12 20:26
That would be **perfect**.

**Comment by LOBsTerr** [comment] 2018-02-21 22:19
PR https://github.com/hechoendrupal/drupal-console/pull/3804

I propose also update other command which use DB connection the same way. So, we can define any db connection from settings.php file

**Comment by LOBsTerr** [comment] 2018-04-23 06:26
it was merged

**Closed by LOBsTerr** 2018-04-23 06:26 UTC
