### ISSUE TITLE
Parse error : drupal.php

### ISSUE THREAD

**Issue by Paulsette** [hechoendrupal/drupal-console#1630] opened 2016-01-04 21:08 UTC
I try to install Drupal Console by following these instructions : https://drupalconsole.com/, but when i "copy configuration files to user home directory" with "drupal init --override" in terminal i have an error :

```
parse error in phar:///usr/local/bin/drupal/bin/drupal.php on line 52
```

Do you know where from comes the problem?

**Comment by seanr** [comment] 2016-01-04 21:20
Make sure you have PHP 5.5.9 or higher, the console has the same requirements as Drupal 8 (with which it was designed to work).  The line in question contains newer syntax that older versions of PHP won’t recognize.


—



Sean Robertson

Senior Developer

DOOR3 Business Applications, Inc.

22 Cortlandt Street, 11th Floor

New York, NY 10007

www.door3.com




212-673-1818 ext. 215

646-912-6720

757-201-4750 (Mobile)

**Comment by Paulsette** [comment] 2016-01-05 09:09
I use the version 5.6.10 of php. 

Moreover, Drupal 8 works, but when I try to install Drupal console I continue to have this error.

For information I use MAMP.

**Comment by jmolivas** [comment] 2016-01-05 16:06
@Paulsette: Is the PHP CLI using the MAMP PHP version, can you try running `php -v` from the CLI and confirm the used PHP version.

**Comment by LOBsTerr** [comment] 2018-05-04 21:44
It looks like there is no reply for long period of time. I'm closing the issue, feel free to reopen it.

**Closed by LOBsTerr** 2018-05-04 21:44 UTC
Labels: bug, need-more-information
