### ISSUE TITLE
[module:uninstall] PHP Fatal error when hook_uninstall call function defined in *.module

### ISSUE THREAD

**Issue by vlabussiere** [hechoendrupal/drupal-console#2107] opened 2016-04-07 09:04 UTC
With Drupal console, I've got a fatal error when I try to uninstall Google analytics module or Piwik module : 

> PHP Fatal error: Call to undefined function google_analytics_clear_js_cache() in /modules/contrib/google_analytics/google_analytics.install on line 16

drupal module:install google_analytics
drupal module:uninstall google_analytics

I've got no problem when I uninstall these modules with Drush or from the Admin UI.

In these modules, in the hook_install, there is a call to a function defined in .module file.
With a module_load_include to this .module file, I can uninstall these modules with the console.

[https://www.drupal.org/node/2701431](https://www.drupal.org/node/2701431)
[Google analytics proposed patch](https://www.drupal.org/files/issues/google_analytics-2701083_uninstall-error_2701083.patch)

**Comment by jmolivas** [comment] 2016-04-07 12:36
@vlabussiere: Thanks a lot for filing this issue! We'll take a look at it as soon as possible!

**Comment by darol100** [comment] 2016-04-08 00:01
@vlabussiere , it seems to be like Drush and your website are not showing the log/errors. Can you check if that issue is also showing in your dblog ?

Because as far I know Drupal Console is not going to do anything special for uninstalling your module compare to the UI.

**Comment by yamlfd** [comment] 2016-04-16 09:50
It looks like it does not include the module file. This one is loaded if you run the GUI. As console seems not loading all required files it causes a undefined function. As Drush does not have this issue you should compare Drush with Console and fix the bug in Console.

**Comment by jmolivas** [comment] 2016-04-16 21:27
@yamlfd Sound fair, the .module is not loaded by the composer autoload. I will have it fixed by loading the .module file.

**Comment by darol100** [comment] 2016-04-24 03:05
> module is not loaded by the composer autoload.

@jmolivas , Should we open an issue in D.O to allow *.module to loaded by composer ?

**Comment by harold20** [comment] 2019-05-29 20:30
I can't reproduce this issue with the DrupalConsole 1.9.0 dev version

**Closed** 2019-05-29 20:32 UTC
Labels: bug
