### ISSUE TITLE
Problem with site:install after composer install of drupal 8.2

### ISSUE THREAD

**Issue by jhmnieuwenhuis** [hechoendrupal/drupal-console#3081] opened 2017-01-07 15:34 UTC
[ site:install ] [ERROR] The specified database connection is not defined: default

when using drupal site:install after composer create-project drupal-composer/drupal-project:8.x-dev
I get an error about the database connection.
The install runs fine after that and everything works.

> cd /var/www/html
> composer create-project drupal-composer/drupal-project:8.x-dev dr8templ --stability dev --no-interaction

> cd /var/www/html/dr8templ/web

>drupal site:install  standard \
    --langcode="en" \
    --db-type="pgsql" \
    --db-host="cstest.jhmnlocal" \
    --db-name="dr8templ" \
    --db-user="dr8" \
    --db-pass="BumperAlex1955&" \
    --db-port="5432" \
    --site-name="Drupal 8 Templatel" \
    --site-mail="jhmnplok@gmail.com" \
    --account-name="drupaluserone" \
    --account-mail="jhmnieuwenhuis@gmail.com.com" \
    --account-pass="ArnoldRieki1928&" \
    --no-interaction
 [ERROR] The specified database connection is not defined: default             

 Starting Drupal 8 install process

 [OK] Your Drupal 8 installation was completed successfully   

Any ideas why this happens ?

**Comment by francescopersico** [comment] 2017-01-17 10:07
I can just say it is not critical. Your site will be installed properly.

**Comment by daften** [comment] 2017-01-20 22:24
Since the latest version of drupal 8.2 and drupal console, I have the same problem, but site:install doesn't actually run for me.
```
➜  web git:(feature/media_update) drupal site:install --db-type="mysql" --db-host="localhost" --db-port="3306" --db-name="digipolisinstall" --db-user="digipolisinstall" --db-pass="digipolisinstall" --site-name="Digipolis install" --site-mail="test@example.com" --account-name="admin" --account-pass="admin" --langcode=en digipolis -vvv


 [ERROR] The specified database connection is not defined: default
```

It does work if --no-interaction is used, but that means there is still something wrong/faulty in the command. The fact the error is thrown in getting the kernel messes with the interaction. It will always fail if it tries to get an option interactively and crashes there.

**Comment by jover** [comment] 2017-01-23 19:05
Same here (with or without --no-interaction):
```
[ERROR] The specified database connection is not defined: default                                                      
// site:install
[ERROR] Invalid multisite, please create multisite using command drupal multisite:new  --site-uri=
```

**Comment by jmolivas** [comment] 2017-01-23 19:53
I just test with latest  RC-15 and it works properly

```
composer create-project drupal-composer/drupal-project:8.x-dev d8.dev no-interaction
drupal site:install --db-user=root --db-pass=root --force --no-interaction
```

**Comment by jmolivas** [comment] 2017-01-23 19:54
@jhmnieuwenhuis @francescopersico @daften @jover 

I just tested with latest  RC-15 and it works properly

```
composer create-project drupal-composer/drupal-project:8.x-dev d8.dev no-interaction
cd d8.dev
drupal site:install --db-user=root --db-pass=root --force --no-interaction
```

**Comment by jover** [comment] 2017-01-24 08:18
I checked my version, and apparently I was using RC-14.
Updated to RC-15 and now it seems to work just fine.

**Comment by daften** [comment] 2017-01-24 10:18
Yes, it works with --no-interaction specified. But please try it without --no-interaction ;)

**Comment by jmolivas** [comment] 2017-01-24 16:31
@jover your error seems related to this https://github.com/hechoendrupal/drupal-console/issues/2770 can you confirm if the fix help you?

**Comment by harold20** [comment] 2019-06-07 17:52
I can't reproduce it using 1.8.0

**Closed** 2019-06-07 18:15 UTC
