### ISSUE TITLE
Installer link not working https://drupalconsole.com/installer

### ISSUE THREAD

**Issue by omargits** [hechoendrupal/drupal-console#4287] opened 2020-11-26 12:55 UTC
### Issue title
https://drupalconsole.com/installer not working gave Error Server Error

Error: Server Error
The server encountered an error and could not complete your request.
Please try again in 30 seconds.

The issue title should comply with the following structure:

[ *ISSUE-GROUP* ] Short description

The *ISSUE-GROUP* should be one of:

* `command:name`
* `console`
* `helper`
* `standard`
* `template`
* `translation`
* `test`
* `docs`

### Problem/Motivation
A brief statement describing why the issue was filed.

**Details to include:**
- Why are we doing this? Above all, a summary should explain why a change is needed, in a few short sentences.

### How to reproduce
Include steps related how to reproduce.

**Details to include:**
- Drupal version (you can obtain this by running `drupal site:status`).
- Console version (you can obtain this by running `composer show | grep drupal/console`).
- Console Launcher version (you can obtain this by running outside of a drupal site `drupal --version`).
- Steps to reproduce
- Include screen-shot or video whenever necessary.

### Solution
A brief description of the proposed fix.

**Details to include:**
- A short summary of the approach proposed or used in the PR.
- Approaches that have been tried and ruled out.
- Links to relevant API documentation or other resources.
- Known workarounds.

**Comment by pixelwhip** [comment] 2020-11-30 00:21
I'm also running to this when trying to install via DrupalVM

```
TASK [geerlingguy.drupal-console : Install Drupal Console.] ********************
fatal: [guttmacher-d9]: FAILED! => {"changed": false, "dest": "/usr/local/bin/drupal", "elapsed": 1, "msg": "Request failed", "response": "HTTP Error 500: Internal Server Error", "status_code": 500, "url": "https://drupalconsole.com/installer"}
```

**Comment by pixelwhip** [comment] 2020-11-30 00:25
Actually, this looks like a duplicate of https://github.com/hechoendrupal/drupal-console/issues/4275

**Comment by xurizaemon** [comment] 2020-12-04 00:31
duplicate of #4263

**Comment by codebymikey** [comment] 2021-02-17 12:08
https://drupalconsole.com/installer seems to be working now.

Hi @jmolivas, would it be possible to attach the phar to the latest release?

This will allow people to install a specific version of the tool going forward.

**Comment by martinym28** [comment] 2022-01-23 05:12
https://drupalconsole.com/installer not working  again?

**Comment by szeberli** [comment] 2022-02-25 17:43
https://drupalconsole.com/installer not working ;(

**Comment by xurizaemon** [comment] 2022-02-25 18:04
It appears that the installer method on that page works until the hosting account reaches its monthly limit.

Note that every post on this thread is from the last week of the month, except https://github.com/hechoendrupal/drupal-console/issues/4287#issuecomment-780513572 (which reports the installer as working on that date).

Please see methods documented in https://github.com/hechoendrupal/drupal-console/issues/4263 to obtain this tool. Posting "it's not working again" will probably not change the situation (unless someone works out how to top up that hosting account?!)

# SEE #4263 RATHER THAN POSTING HERE

**Comment by LOBsTerr** [comment] 2022-09-16 11:42
Close as a duplicated

**Closed by LOBsTerr** 2022-09-16 11:42 UTC
