### ISSUE TITLE
Multisite Uri Option Not Working?

### ISSUE THREAD

**Issue by 58bits** [hechoendrupal/drupal-console#2002] opened 2016-03-08 00:44 UTC
Great tool, however I'm not sure that -l, or -uri options are working for multisite.

I have a sites directory with 'default' and 'my.site.com'. There is no active settings.php file in 'default'.

I have a sites.php file containing an alias to the 'my.site.com'

However when I try  `drupal list --uri=http://my.site.com`  - from the Drupal root, I receive a message saying that "[WARNING] In order to list all of the available commands you should install drupal first."

If I take a copy of the settings.php file from my.site.com, and temporarily place it in the 'default' site directory - drupal console works as expected.

**Comment by Anicky** [comment] 2016-03-18 15:48
I have the same problem too. However, I don't have a multisite. But, even if there is only one site, I don't use "default" directory for my project.

The problem is in DrupalConsole/src/Helper/DrupalHelper.php.
`   /**
     * @return bool
     */
    public function isConnectionInfo()
    {
        $settingsPath = sprintf('%s/%s', $this->root, self::DEFAULT_SETTINGS_PHP);
        if (!file_exists($settingsPath)) {
            return false;
        }
        if (Database::getConnectionInfo()) {
            return true;
        }
        return false;
    }`

Instead of looking in the "default" directory, it would check first if there is settings.php in current directory.

**Comment by jmolivas** [comment] 2016-03-31 08:52
I will be taking care of this for the release on April 7.

**Comment by toabi** [comment] 2016-04-15 06:39
I have the same symptoms when using `site:install` … it always installs into the default directory, not respecting the `sites.php` which folder it should use.

**Comment by jonpugh** [comment] 2016-05-15 19:46
@jmolivas this is the issue I talked to you about at DrupalCon.

**Comment by mstenta** [comment] 2016-05-16 12:40
I did a little testing, based on the comment by @Anicky above. I confirmed that the <code>isConnectionInfo()</code> method is always looking at sites/default/settings.php, even if you use the <code>--uri</code> parameter with your command.

I am specifically testing with the <code>generate</code> commands, but I would assume that all commands are affected. I did some digging to try to find a solution, but I'm not familiar enough with Symfony Console conventions to know how to pass input parameters to this <code>DrupalHelper</code> class. Is it possible?

As a separate question: I wonder if the <code>generate</code> commands should not require a database connection to work? They are not interacting with the site database, are they? Or perhaps the database connection assumption is so low-level that it would be hard to make an exception for certain commands like that? This can be a separate feature request perhaps... just brainstorming. :-)

**Comment by acrolyt** [comment] 2016-05-25 09:30
We encountered the same issue. Any news here?

**Comment by esolitos** [comment] 2016-05-25 09:32
I'll just drop it here: at the moment I have work around this using a script that symlinks `sites/default` to the desired local site, it's not a solution, but it saves me quite some time. :)
Ref here: https://github.com/esolitos/drupal-utility/blob/feature/d8-relink-default-site/bin/symlink-default-site

**Comment by mstenta** [comment] 2016-05-25 12:51
The workaround mentioned by @esolitos works for a normal Drupal multi-site installation. It does not work for multisites installed via Aegir, however. This is because Aegir takes an extra security precaution and does not store the database credentials in settings.php. See #2263 

My workaround for that has been to create a simple settings.php file in the default folder with the actual database credentials hard-coded. This allows Console to find the database... but obviously it only works for one site in the multi-site platform.

**Comment by mickaelperrin** [comment] 2016-06-22 14:42
The adequate settings.php file seems to be found and read during the drupal kernel booting.
I just commented out the test on file settings and got it working on a multisite install.

Why the `Database::getConnectionInfo()` is not sufficient ?

**Comment by mickaelperrin** [comment] 2016-10-25 10:43
@jmolivas it looks like that since my latest comment, things have been totally reworked. I didn't find anymore the use of the `uri` option and tried to resolve this issue in the #2850 PR.

**Comment by mstenta** [comment] 2017-08-30 17:01
@mickaelperrin Since #2850 was merged, does that mean that this issue is fixed?

**Comment by ao2** [comment] 2018-03-13 22:11
One issue I found about the the `uri` option is that it does not affect the site **base path**, for example, this command returns an unexpected result:
```
echo "base_path();" | ./vendor/bin/drupal --uri='http://example.net/~ao2/test_site/web' shell
```

I would expect it to return `/~ao2/test_site/web/` but it always returns `/`.

This is because `Drupal::boot()` does not take into account the path when setting $_SERVER['REQUEST_URI']` in `src/Bootstrap/Drupal.php`.

That is done in `src/Command/Test/RunCommand.php` BTW, maybe some duplication can be avoided too?

The issue affects also the drupal `Url` class when creating `internal` and `base` URLs.

For some details about why setting the **base path** correctly is important, look at a similar bug report for Drush: https://github.com/drush-ops/drush/issues/3463

Should I file a separate issue for this **base path** problem?

**Comment by harold20** [comment] 2019-05-28 18:06
Hi @ao2, This PR should fix the base path https://github.com/hechoendrupal/drupal-console/pull/4064

**Closed** 2019-05-28 18:57 UTC
