### ISSUE TITLE
[site:mode] Call to undefined method Symfony\Component\Yaml\Inline::isHash() in Symfony\Component\Yaml\Dumper->dump()

### ISSUE THREAD

**Issue by kevin-coyle** [hechoendrupal/drupal-console#2466] opened 2016-06-27 16:41 UTC
Getting this on Drupal 8.1.3.

This is when I try and run `drupal site:mode dev`

**Comment by enzolutions** [comment] 2016-06-27 19:43
@kevin-coyle I tried with Drupal 8.1.3 and Drupal Console 1.0-beta2 and I can't reproduce the error

**Comment by louisbl** [comment] 2016-06-28 09:33
I have the same error on every drupal console command. Some sommands works, some not.

`drupal`
```sh
 ❯ drupal                                                                  [11:31:27]
Starting voilebp_data_1

Drupal Console (1.0.0-beta2) | Current Drupal (8.1.3)
=====================================================

Copy configuration files to user home directory.

   drupal init --override

Download, install and serve Drupal 8

   drupal chain --file=~/.console/chain/quick-start.yml

Create a new Drupal project

   drupal site:new drupal8.dev --latest

Install a Drupal project

   drupal site:install

Lists all available commands

   drupal list

Update project to the latest version.
-------------------------------------

   drupal self-update

 // settings:set

Fatal error: Call to undefined method Symfony\Component\Yaml\Inline::isHash() in /var/www/vendor/symfony/yaml/Dumper.php on line 61
```

`drupal config:diff`
```sh
❯ drupal config:diff                                                      [11:22:24]
 Config directory: [sync]:
  [0] sync
 >

 ------------ ------------------------------- -----------
  Collection   Configuration item              Operation
 ------------ ------------------------------- -----------
               search_api.index.idx_contenus   update
 ------------ ------------------------------- -----------

 // settings:set

Fatal error: Call to undefined method Symfony\Component\Yaml\Inline::isHash() in /var/www/vendor/symfony/yaml/Dumper.php on line 61
```

`drupal config:export` (nothing is exported)
```sh
 ❯ drupal config:export                                                    [11:23:36]

Fatal error: Call to undefined method Symfony\Component\Yaml\Inline::isHash() in /var/www/vendor/symfony/yaml/Dumper.php on line 61
```

**Comment by kevin-coyle** [comment] 2016-06-28 17:37
This doesn't happen if I install drupal console through composer. It does if I use it on a project that uses composer manager with the phar installation method.

**Comment by jmolivas** [comment] 2016-06-29 06:38
@kevin-coyle @louisbl New release 1.0.0-beta3 was tagged, can you try if the error still happening?

**Comment by FatherShawn** [comment] 2016-06-29 14:02
@jmolivas I just updated a vm to beta3 - this error persists using phar based installation.  Installing via `composer global require drupal/console:1.0.0-beta3` I do not get this error.

**Comment by jamiehollern** [comment] 2016-07-05 12:44
This is happening to me too when I run `drupal site:mode`. I self updated to beta3 and it persists.

```
PHP Fatal error:  Call to undefined method Symfony\Component\Yaml\Inline::isHash() in /docroot/vendor/symfony/yaml/Dumper.php on line 61
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/drupal:0
PHP   2. require() /usr/local/bin/drupal:10
PHP   3. require() phar:///usr/local/bin/drupal/bin/drupal:3
PHP   4. Symfony\Component\Console\Application->run() phar:///usr/local/bin/drupal/bin/drupal.php:115
PHP   5. Drupal\Console\Application->doRun() phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php:123
PHP   6. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/drupal/src/Application.php:292
PHP   7. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php:192
PHP   8. Symfony\Component\Console\Command\Command->run() phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php:860
PHP   9. Drupal\Console\Command\Site\ModeCommand->execute() phar:///usr/local/bin/drupal/vendor/symfony/console/Command/Command.php:259
PHP  10. Drupal\Console\Command\Site\ModeCommand->overrideServices() phar:///usr/local/bin/drupal/src/Command/Site/ModeCommand.php:70
PHP  11. Symfony\Component\Yaml\Yaml::dump() phar:///usr/local/bin/drupal/src/Command/Site/ModeCommand.php:177
PHP  12. Symfony\Component\Yaml\Dumper->dump() /docroot/vendor/symfony/yaml/Yaml.php:98
```

**Comment by jmolivas** [comment] 2016-07-05 13:31
@jamiehollern is this a global installation ?

**Comment by jamiehollern** [comment] 2016-07-05 14:05
@jmolivas Yes. All project composer dependencies are up to date and so is Drupal Console.

**Comment by vifito** [comment] 2016-07-28 09:51
Drupal Console is using the Yaml class from drupal vendor folder
MY WORKAROUND (dont recommended!!!) modify Dumper class in drupal installation at 61 line

--- Dumper.old.php  2016-07-28 09:39:27.642653445 +0000
+++ Dumper.php  2016-07-28 09:40:02.554379252 +0000
@@ -58,7 +58,7 @@
if ($inline <= 0 || !is_array($input) || empty($input)) {
$output .= $prefix.Inline::dump($input, $exceptionOnInvalidType, $objectSupport);
} else {
-            $isAHash = Inline::isHash($input);
+            $isAHash = array_keys($input) !== range(0, count($input) - 1);

foreach ($input as $key => $value) {
$willBeInlined = $inline - 1 <= 0 || !is_array($value) || empty($value);

**Comment by 4alldigital** [comment] 2016-07-30 14:56
I also get this on pretty much ALL commands.

``` // settings:set
Error: Call to undefined method Symfony\Component\Yaml\Inline::isHash() in /docker/playground/drupal8.docker/vendor/symfony/yaml/Dumper.php on line 61
Error: Call to undefined method Symfony\Component\Yaml\Inline::isHash() in Symfony\Component\Yaml\Dumper->dump() (line 61 of /docker/playground/drupal8.docker/vendor/symfony/yaml/Dumper.php).```

Drupal version 8.1.7
Drupalconsole version 1.0.0-beta4

**Comment by jmolivas** [comment] 2016-07-30 15:38
@4alldigital is your site based on DrupalComposer project?

**Comment by jmolivas** [comment] 2016-07-30 15:59
@4alldigital related issue https://github.com/hechoendrupal/DrupalConsole/issues/2525

**Comment by 4alldigital** [comment] 2016-07-30 16:53
@jmolivas no, Drupalconsole based.  But, I just had some unrelated issues, and restarted my docker environment and now the error has gone away.  So, now I can't reproduce.  

May have been a network issue, or directory permissions.  If I can reproduce consistently, I'\ll come back and report. sorry.

**Comment by 4alldigital** [comment] 2016-08-01 16:22
@jmolivas  pretty sure this my issue was same as the related issue you have marked. updated version of Symfony YAML.  2.8.7+ resolves the issue.

**Comment by 4alldigital** [comment] 2016-08-02 11:46
Ok, so I'm getting this again, despite the function 100% existing 

run : drupal config:export
```Error: Call to undefined method Symfony\Component\Yaml\Inline::isHash() in /docker/general/fatbeehive/project-literacy/repository/vendor/symfony/yaml/Dumper.php on line 61
Error: Call to undefined method Symfony\Component\Yaml\Inline::isHash() in Symfony\Component\Yaml\Dumper->dump() (line 61 of /docker/general/fatbeehive/project-literacy/repository/vendor/symfony/yaml/Dumper.php).
```

run: grep -rFHin 'public static function isHash' ../vendor/symfony/yaml/

```../vendor/symfony/yaml/Inline.php:169:    public static function isHash(array $value)
```
anything I can do to help debug this?  as it seems re-produceable...

**Comment by enzolutions** [comment] 2016-08-02 12:58
@jmolivas did you solve this with @lnunesbr right?

**Comment by jmolivas** [comment] 2016-08-02 13:54
Seem we need  to lock the `symfony/yaml` component version

**Comment by jmolivas** [comment] 2016-08-02 13:55
Let me find out which version introduce the bug to lock to the previous one.

**Comment by 4alldigital** [comment] 2016-08-02 13:56
Not sure its the version issue (although the function is missing in 2.8.0 -> 2.8.6). See above, the function IS present, but drupal console commands triggering `Error: Call to undefined method`.

**Comment by 4alldigital** [comment] 2016-08-02 13:59
also...disclaimer.... (I have 0 experience of Symfony), is it normal/standard that changelog.md doesn't reflect version/tag's e.g. https://github.com/symfony/yaml/blob/v2.8.9/CHANGELOG.md . says 2.8.0. took me a little while to track down the current symfony/yaml version I had installed.

**Comment by zuernBernhard** [comment] 2016-08-02 13:59
Same problem here, have a site with drupal composer template. Try to export config after enabling a new module:

`$ composer update symfony/yaml
Gathering patches for root package.
Loading composer repositories with package information                                                              Updating dependencies (including require-dev)         Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
  - Removing symfony/yaml (v2.8.8)
  - Installing symfony/yaml (v2.8.9)
    Downloading: 100%         

Writing lock file
Generating autoload files
> DrupalProject\composer\ScriptHandler::buildScaffold
> DrupalProject\composer\ScriptHandler::createRequiredFiles

$ drupal config:export:single core.extension
 Configuration(s) exported sucessfully
Error: Call to undefined method Symfony\Component\Yaml\Inline::isHash() in /var/www/project/vendor/symfony/yaml/Dumper.php on line 61
Error: Call to undefined method Symfony\Component\Yaml\Inline::isHash() in Symfony\Component\Yaml\Dumper->dump() (line 61 of /var/www/project/vendor/symfony/yaml/Dumper.php).

`

**Comment by jmolivas** [comment] 2016-08-02 14:08
@4alldigital to see all f the installed libraries you can execute
```
composer show
``` 
to see a particular library information 
```
composer show symfony/yaml
```

**Comment by 4alldigital** [comment] 2016-08-02 14:13
@jmolivas thanks

**Comment by jmolivas** [comment] 2016-08-02 14:17
Related issue https://github.com/hechoendrupal/DrupalConsole/issues/2525

**Comment by 4alldigital** [comment] 2016-08-02 16:20
ok, so Im confused. when I `composer require symfony/yaml 2.8.6`, confirmed in use via `compose show` (symfony/yaml  v2.8.6  Symfony Yaml Component) things start working.

eg. drupal config:export works fine.

`composer require symfony/yaml 2.8.7` + all trigger the error:  **Error: Call to undefined method Symfony\Component\Yaml\Inline::isHash()**

2.8.6 is the last version that DID NOT have `public static function isHash(...` in it : https://github.com/symfony/yaml/blob/v2.8.7/Inline.php#L169

@jmolivas thoughts? Am I missing something?  NB: v2.8.6 things are working for me.

**Comment by 4alldigital** [comment] 2016-08-02 16:21
@zuernBernhard can you try **symfony/yaml 2.8.6** ?

**Comment by nrambeck** [comment] 2016-08-03 20:51
I'm having this same problem as well. My site is based on DrupalComposer. 

`Drupal Console (1.0.0-beta5) | Current Drupal ("8.1.8")`

Requiring `symfony/yaml#2.8.6` in my composer file as suggested above did solve the problem.

**Comment by jmolivas** [comment] 2016-08-03 20:55
I can for force for now DrupalConsole `composer.json` file https://github.com/hechoendrupal/DrupalConsole/blob/master/composer.json#L53 to v2.8.6 until we make the required changes to support the latest `symfony.yaml` version.

**Comment by zuernBernhard** [comment] 2016-08-04 08:04
Yes that also quick-fixes it for 
me.

**Comment by ybabel** [comment] 2016-08-10 15:28
fresh console install today on last drupal 8. Same problem.
vifito workaround worked.
waiting for next release.

**Comment by bensinjin** [comment] 2016-08-16 20:47
I found this worked when using https://github.com/drupal-composer/drupal-project.

1) Initially use drupalconsole located at vendor/bin/drupal in your codebase root. ie, vendor/bin/drupal config:export
2) After using it once the global one appears to start working? It may just be defaulting to that one anyways it worked for me.

**Comment by acha5066** [comment] 2016-11-29 03:21
Even though it might be fixed in one of the 1.x releases when you run php -r "readfile('https://drupalconsole.com/installer');" > drupal.phar you are given the 0.11.3 release which has this bug. And as a lot of people will be downloading that way, they will be getting this bug too. So maybe update the phar to a newer release?

**Comment by jmolivas** [comment] 2017-05-29 19:15
Closing this one. Feel free to re-open if still happening after updating to the latest version.

**Closed by jmolivas** 2017-05-29 19:15 UTC
Labels: works-as-expected
